Web/FLS.LC.Web/FLS.LC.Web/Controllers/Master/GarmentReturnCauseController.cs
using FLS.LC.Web.Models.Master;
using FLS.LC.Web.Services.Master.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FLS.LC.Web.Controllers.Master
{
    public class GarmentReturnCauseController : Controller
    {
        IGarmentReturnCause _garmentReturnCause;
        public GarmentReturnCauseController(IGarmentReturnCause garmentReturnCause)
        {
            _garmentReturnCause = garmentReturnCause;
        }
        public async Task<IActionResult> GarmentReturnCause()
        {
            try
            {
                lstGarmentReturnCauseResponseDto lstgarmentReturnCauseResponseDto = new lstGarmentReturnCauseResponseDto();
                var operationResponse = await _garmentReturnCause.GetRegisteredGarmentReturnCauseAsync();
                if (operationResponse.Count > 0)
                {
                    lstgarmentReturnCauseResponseDto.lstGarmentReturnCauseResponse = operationResponse;
                    lstgarmentReturnCauseResponseDto.ShowSuccessAlert = true;
                    return View(lstgarmentReturnCauseResponseDto);
                }
                else
                {
                    return View(lstgarmentReturnCauseResponseDto);
                }
            }
            catch (Exception ex)
            {
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PostGarmentsReturnCause(GarmentReturnCausePostDto garmentReturnCausePostDto)
        {
            var operationResponse = await _garmentReturnCause.RegisterGarmentReturnCauseAsync(garmentReturnCausePostDto);
            if (true)
            {
                return Json("true");
            }
        }
    }
}

Web/FLS.LC.Web/FLS.LC.Web/Views/GarmentReturnCause/GarmentReturnCause.cshtml
@model FLS.LC.Web.Models.Master.lstGarmentReturnCauseResponseDto
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="~/css/lc.css" asp-append-version="true" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <div>
        <div class="position-absolute gReturnCause-main-content gReturnCause-main-min-width">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="gReturnCause-white-box gReturnCause-border-primary-color">
                            <div class="gReturnCause-bg-color d-flex flex-wrap justify-content-between align-items-center p-2">
                                <label class="mb-0 gReturnCause-font-size">Cloth Return Cause</label>
                            </div>
                            <form method="get" id="garmentRemarks" enctype="multipart/form-data" asp-controller="GarmentReturnCause" asp-action="GarmentReturnCause" class="p-3" novalidate autocomplete="off">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group required d-flex my-2">
                                            <div class="input-group input-group-sm">
                                                <label class="input-group-text gReturnCause-font-size">Cloth Return Cause</label>
                                                @Html.TextBoxFor(m => m.GreReturnCauseDescription, new { id = "GreReturnCauseDescription", @class = "form-control", @placeholder = "Kindly Enter Cloth Return Cause" })
                                            </div>
                                            <i class="fa fa-info-circle pl-1 pt-1 gReturnCause-text-primary-color"
                                               data-bs-toggle="tooltip"
                                               title='This will be used as a reason when clothes are returned without processing'></i>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12 d-flex flex-wrap justify-content-start">
                                        <button id="btnOperation" type="button" onclick="PostGarmentReturnCause()" class="btn btn-info gReturnCause-font my-2 mr-2">
                                            <i class="fa fa-floppy-o"></i>
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 gReturnCause-margin-bottom">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-sm">
                                <thead class="bg-secondary">
                                    <tr>
                                        <th class="text-center text-white gDescription-font-size">Operation</th>
                                        <th class="text-center text-white gDescription-font-size">Id</th>
                                        <th class="text-center text-white gReturnCause-font-size">Cloth Return Cause</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.lstGarmentReturnCauseResponse == null || Model.lstGarmentReturnCauseResponse.Count == 0 || Model.ShowSuccessAlert == false)
                                    {
                                        <tr style="text-align:center">
                                            <td>
                                                <label> <b> No Registered Garment Return Cause Found.... </b> </label>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        @foreach (var garmentReturnCause in Model.lstGarmentReturnCauseResponse)
                                        {
                                            <tr class="border">
                                                <td class="text-center"><a class="btnselect btn btn-primary">Select</a></td>
                                                <td class="text-center">@garmentReturnCause.GrecId</td>
                                                <td class="text-center">@garmentReturnCause.GreReturnCauseDescription</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                            <input type="hidden" id="hdngarmentReturnCauseDescriptionOldValue" />
                            <input type="hidden" id="hdngarmentReturnCauseId" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" asp-append-version="true"></script>
        <script type="text/javascript">
            function PostGarmentReturnCause() {
                var garmentReturnCauseDescriptionOldValue = $("#garmentReturnCauseDescriptionOldValue").val();
                var garmentReturnCauseDescriptionNewValue = $("#GreReturnCauseDescription").val();
                var garmentReturnCauseId = $("#garmentReturnCauseId").val();
                var model = {
                    'garmentReturnCauseOldValue': garmentReturnCauseDescriptionOldValue.trim(),
                    'garmentReturnCauseNewValue': garmentReturnCauseDescriptionNewValue.trim(),
                    'GrecId': garmentReturnCauseId
                }
                  $.ajax({
                url: '@Url.Action("PostGarmentsReturnCause", "GarmentReturnCause")',
                type: "POST",
                data: model,
                success: function (result) {
                    if (result == "true") {
                        $("#garmentRemarks").submit();
                    }
                }
            });
            }
            $(document).ready(function () {
            });
            $('.btnselect').click(function (e) {
                $("#btnOperation").html('Update');
                var currentRow = $(this).closest("tr");
                var selectedGarmentReturnCauseDescription = currentRow.find("td:eq(2)").text();
                var selectedGarmentReturnCauseId = currentRow.find("td:eq(1)").text();
                $("#hdngarmentReturnCauseDescriptionOldValue").val(selectedGarmentReturnCauseDescription);
                $("#hdngarmentReturnCauseId").val(selectedGarmentReturnCauseId);
                $("#GreReturnCauseDescription").val(selectedGarmentReturnCauseDescription);
            });
        </script>
    </div>
</body>

</html>