Web/FLS.LC.Web/FLS.LC.Web/Controllers/Master/GarmentCheckingStaffController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FLS.LC.Web.Models.Master;
using FLS.LC.Web.Services.Master.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FLS.LC.Web.Controllers.Master
{
    public class GarmentCheckingStaffController : Controller
    {
        IGarmentCheckingStaffConfig _garmentcheckingstaff;
        IStoreApiService _StoreApiService;
        private readonly IMemoryCache _cache;
        public GarmentCheckingStaffController(IMemoryCache memoryCache, IStoreApiService storeApiService, IGarmentCheckingStaffConfig garmentcheckingstaff)
        {
            _garmentcheckingstaff = garmentcheckingstaff;
            _StoreApiService = storeApiService;
            _cache = memoryCache;
        }
        private void AdduserStoresDataToCache(IReadOnlyCollection<UserStoreDetailDtotemp> userStores)
        {
            var memoryCacheEntryOptions = new MemoryCacheEntryOptions
            {
                AbsoluteExpiration = DateTime.Now.AddMinutes(1),
                Priority = CacheItemPriority.High,
                SlidingExpiration = TimeSpan.FromMinutes(5),
            };
            _cache.Set("userStoresCachedKey", userStores, memoryCacheEntryOptions);
        }
        public async Task<IActionResult> GarmentCheckingStaff()
        {
            try
            {
                GarmentCheckingStaffResponseDto GarmentCheckingStaffResponseDto = new GarmentCheckingStaffResponseDto();
                string UserEmail = HttpContext.Session.GetString("UserEmail");
                GarmentCheckingStaffResponseDto.GpcUsremail = UserEmail;
                var existinguserStoresDataInCache = (IReadOnlyCollection<UserStoreDetailDtotemp>)_cache.Get("userStoresCachedKey");
                if (existinguserStoresDataInCache == null)
                {
                    var regStores = await _StoreApiService.RegisteredStoresAsync(UserEmail);
                    AdduserStoresDataToCache(regStores);
                    ViewBag.RegisteredUserStoresListItems = regStores.Distinct().Select(i => new SelectListItem() { Text = i.UstName, Value = i.UstName.ToString() }).ToList();
                }
                else
                {
                    ViewBag.RegisteredUserStoresListItems = existinguserStoresDataInCache.Distinct().Select(i => new SelectListItem() { Text = i.UstName, Value = i.UstName.ToString() }).ToList();
                }
                var operationResponse = await _garmentcheckingstaff.GetRegisteredGarmentRemarksAsync();
                if (operationResponse.Count > 0)
                {
                    GarmentCheckingStaffResponseDto.lstGarmentCheckingStaffResponseDto = operationResponse;
                    GarmentCheckingStaffResponseDto.ShowSuccessAlert = true;
                    return View(GarmentCheckingStaffResponseDto);
                }
                else
                {
                    return View(GarmentCheckingStaffResponseDto);
                }
            }
            catch (Exception ex)
            {
            }
            return View();
        }


        [HttpPost]
        public async Task<JsonResult> PostGarmentCheckingStaff(string useremail, string userstore, string employeeName, string employeeAddress, string employeemobileno
            , string employeeemail)
        {
            try
            {


                if (string.IsNullOrEmpty(useremail) || string.IsNullOrEmpty(userstore))
                { return Json(false); }
                var garmentCheckingStaffRequestDto = new GarmentCheckingStaffRequestDto()
                {
                    GpcUsremail = useremail,
                    GpcUstname = userstore,
                    GcsEmployeeName = employeeName,
                    GcsEmployeeAddress = employeeAddress,
                    GcsEmployeeMobileNo = Convert.ToInt64(employeemobileno),
                    GcsEmployeeEmail = employeeemail
                };
                var operationResponse = await _garmentcheckingstaff.RegisterGarmentCheckingStaffAsync(garmentCheckingStaffRequestDto);
                if (operationResponse == true)
                {
                    return Json("true");
                }
                return Json("false");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Web/FLS.LC.Web/FLS.LC.Web/Views/GarmentCheckingStaff/GarmentCheckingStaff.cshtml
@model FLS.LC.Web.Models.Master.GarmentCheckingStaffResponseDto
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="~/css/lc.css" asp-append-version="true" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/b7245b8622.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <div>
        <div class="position-absolute garmentCheckingStaff-main-content garmentCheckingStaff-main-min-width">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="garmentCheckingStaff-white-box garmentCheckingStaff-border-primary-color">
                            <div class="garmentCheckingStaff-bg-color d-flex flex-wrap justify-content-between align-items-center p-2">
                                <label class="mb-0 garmentCheckingStaff-font-size">Employee</label>
                            </div>
                            @Html.Hidden("usrEmail", Model.GpcUsremail);
                            <form method="get" id="garmentCheckingStaff" enctype="multipart/form-data" asp-controller="GarmentCheckingStaff" asp-action="GarmentCheckingStaff" class="p-3" novalidate autocomplete="off">
                                <div class="row">
                                    <div class="col-sm-7">
                                        <div class="form-group required d-flex">
                                            <div class="input-group input-group-sm">
                                                <label class="input-group-text">Store Name</label>
                                                @Html.DropDownListFor(model => model.GpcUstname, ViewBag.RegisteredUserStoresListItems as IEnumerable<SelectListItem>, "Select", new { id = "StcUstName" })
                                                <i class="fa fa-info-circle pl-1 pt-1 gListConfiguration-text-primary-color"
                                                   data-bs-toggle="tooltip"
                                                   title="Select the store you wish to add Garment Checking Staff Employee"></i>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group required d-flex my-2">
                                            <div class="input-group input-group-sm">
                                                <i class="input-border fa fa-user"></i>
                                                <select id="EmployeeType" class="form-select">
                                                    <option value="Mr">Mr</option>
                                                    <option value="Ms">Ms</option>
                                                    <option value="Mrs">Mrs</option>
                                                    <option value="Dr">Dr</option>
                                                    <option value="M/S">M/S</option>
                                                </select>
                                                @Html.TextBoxFor(m => m.GcsEmployeeName, new { id = "GcsEmployeeName", @class = "form-control", @placeholder = "Kindly Enter Employee Name" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group required d-flex my-2">
                                            <div class="input-group input-group-sm">
                                                <i class="input-border fa fa-building-o"></i>
                                                @Html.TextAreaFor(m => m.GcsEmployeeAddress, new { id = "GcsEmployeeAddress", @class = "form-control", @placeholder = "Employee Address" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group d-flex my-2">
                                            <div class="input-group input-group-sm">
                                                <i class="input-border fa fa-phone"></i>
                                                @Html.TextBoxFor(m => m.GcsEmployeeMobileNo, new { id = "GcsEmployeeMobileNo", @class = "form-control", @placeholder = "Kindly Enter Employee Mobile No" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group d-flex my-2">
                                            <div class="input-group input-group-sm">
                                                <i class="input-border fa fa-envelope"></i>
                                                @Html.TextBoxFor(m => m.GcsEmployeeEmail, new { id = "GcsEmployeeEmail", @class = "form-control", @placeholder = "Kindly Enter Employee Email" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12 d-flex flex-wrap justify-content-start">
                                        <button id="btnOperation" onclick="PostGarmentCheckingStaff()" type="button" class="btn btn-info garmentCheckingStaff-font my-2 mr-2">
                                            <i class="fa fa-floppy-o"></i>
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 garmentCheckingStaff-margin-bottom">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-sm">
                                <thead class="bg-secondary">
                                    <tr>
                                        <th class="text-center text-white garmentCheckingStaff-font-size">Operation</th>
                                        <th class="text-center text-white garmentCheckingStaff-font-size">Name</th>
                                        <th class="text-center text-white garmentCheckingStaff-font-size">Address</th>
                                        <th class="text-center text-white garmentCheckingStaff-font-size">Mobile</th>
                                        <th class="text-center text-white garmentCheckingStaff-font-size">Email</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.lstGarmentCheckingStaffResponseDto == null || Model.lstGarmentCheckingStaffResponseDto.Count == 0 || Model.ShowSuccessAlert == false)
                                    {
                                        <tr style="text-align:center">
                                            <td>
                                                <label> <b> No Registered Garment Checking Staff Found.... </b> </label>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        @foreach (var garmentCheckingStaff in Model.lstGarmentCheckingStaffResponseDto)
                                        {
                                            <tr class="border">
                                                <td class="text-center"><a class="btnselect btn btn-primary">Select</a></td>
                                                <td class="text-center">@garmentCheckingStaff.GcsEmployeeName</td>
                                                <td class="text-center">@garmentCheckingStaff.GcsEmployeeAddress</td>
                                                <td class="text-center">@garmentCheckingStaff.GcsEmployeeMobileNo</td>
                                                <td class="text-center">@garmentCheckingStaff.GcsEmployeeEmail</td>
                                                @Html.Hidden("ustName", @garmentCheckingStaff.GpcUstname, new { @id = "ustName" });
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" asp-append-version="true"></script>
    <script>
        function PostGarmentCheckingStaff() {
            var selectedEmployeeName = $("#GcsEmployeeName").val();
            var selectedEmployeeType = $("#EmployeeType").val();
            var selectedEmployeeAddress = $("#GcsEmployeeAddress").val();
            var selectedGcsEmployeeMobileNo = $("#GcsEmployeeMobileNo").val();
            var selectedGcsEmployeeEmail = $("#GcsEmployeeEmail").val();
            var selectOptions = $('#StcUstName option:selected');
            if (selectOptions.length > 0) {
                var resultString = "";
                resultString = selectOptions.text();
                if (resultString == "Select") {
                    alert("Please Select Store to Search Garment");
                    $('#garmentSearch').val("");
                    return false;
                }
            }
            var model = {
                'useremail': $("#usrEmail").val().trim(),
                'userstore': resultString.trim(),
                'employeeName': selectedEmployeeName.trim(),
                'employeeAddress': selectedEmployeeAddress.trim(),
                'employeemobileno': selectedGcsEmployeeMobileNo,
                'employeeemail': selectedGcsEmployeeEmail.trim()
            }
            $.ajax({
                url: '@Url.Action("PostGarmentCheckingStaff", "GarmentCheckingStaff")',
                type: "POST",
                data: model,
                success: function (result) {
                    if (result == "true") {
                        $("#garmentCheckingStaff").submit();
                    }
                }
            });

        }
        $(document).ready(function () {
        });
        $('.btnselect').click(function (e) {
            $("#btnOperation").html('Update');
            var currentRow = $(this).closest("tr");
            var selectedEmployeeName = currentRow.find("td:eq(1)").text();
            var selectedEmployeeAddress = currentRow.find("td:eq(2)").text();
            var selectedEmployeeMobileNo = currentRow.find("td:eq(3)").text();
            var selectedEmployeeEmail = currentRow.find("td:eq(4)").text();
            $("#GcsEmployeeName").val(selectedEmployeeName);
            $("#GcsEmployeeAddress").val(selectedEmployeeAddress);
            $("#GcsEmployeeMobileNo").val(selectedEmployeeMobileNo);
            $("#GcsEmployeeEmail").val(selectedEmployeeEmail);
            $("#StcUstName").val($("#ustName").val());
            $("#GcsEmployeeName").prop("readonly", true);
            $("#EmployeeType").prop("readonly", true);
        });

    </script>
</body>
</html>